# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b98e7b9614665b87caf83ebaa9c9c2ecd24ce0cc69db97bf7591d106237415ba6de34e3c5a13ca6b4146ab6375de358fb4387b4aeaadc74f458d36fc0071b386

test:
  secret_key_base: 36144733dedb1fd5c28b2afc7950e3f7c0923b3d458bd39b470f78c920e8b7cb6cb09c57e26e25aa43154c8f5e2239143d26405c63b5402f0347f77526187bd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
